name: Release & Publish

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [master]

jobs:
  release-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write   # to create releases
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Check version change
        id: check_version
        run: |
          # Get current version
          CURRENT_VERSION=$(grep -m1 'version = ' pyproject.toml | cut -d'"' -f2)
          echo "Current version: $CURRENT_VERSION"
          
          # Get previous version
          git checkout HEAD^1
          PREVIOUS_VERSION=$(grep -m1 'version = ' pyproject.toml | cut -d'"' -f2)
          echo "Previous version: $PREVIOUS_VERSION"
          git checkout -
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create GitHub Release
        if: steps.check_version.outputs.changed == 'true'
        uses: softprops/action-gh-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check_version.outputs.version }}
          name: Release v${{ steps.check_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Install build dependencies
        if: steps.check_version.outputs.changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        if: steps.check_version.outputs.changed == 'true'
        run: python -m build

      - name: Publish to PyPI
        if: steps.check_version.outputs.changed == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/* 